version: '3.8'

services:
  haoma:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data:ro
      - haoma_db:/root
    environment:
      - GIN_MODE=release
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  haoma_db:
